### ISSUE TITLE
Not helpfull error information 

### ISSUE THREAD

**Issue by dgogoasa** [pedrohdz/py-lambda-packer#6]
I have this exception when running py-lambda-packer. It seems like a file path is empty (None) but I have no idea what file or path or what is expected to be there. The trace is not helpful and the lambda doesn't recover, so my build fails and I don't know why. 

Traceback (most recent call last):
  File "/usr/local/bin/py-lambda-packer", line 8, in <module>
    sys.exit(entry_point())
  File "/usr/local/lib/python3.6/dist-packages/plpacker/cli.py", line 161, in entry_point
    packer.build()
  File "/usr/local/lib/python3.6/dist-packages/plpacker/pylambdapacker.py", line 25, in build
    if self.virtual_env.filesets:
  File "/usr/local/lib/python3.6/dist-packages/plpacker/virtualenv.py", line 101, in filesets
    excludes=self.fileset_excludes)
  File "/usr/local/lib/python3.6/dist-packages/plpacker/fileset.py", line 36, in __init__
    self.fileset = self._expand_fileset()
  File "/usr/local/lib/python3.6/dist-packages/plpacker/fileset.py", line 58, in _expand_fileset
    self._expand_glob(exclude, self.followlinks))
  File "/usr/local/lib/python3.6/dist-packages/plpacker/fileset.py", line 63, in _expand_glob
    if os.path.isabs(expression):
  File "/usr/lib/python3.6/posixpath.py", line 66, in isabs
    s = os.fspath(s)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by dgogoasa** [comment]
I found the answer. In the default_excludes section of the py-lambda-packer.yaml file I had an empty string after a a dsh (last line). Removing it was the solution to my problem.
default_excludes:
  - easy_install.*
  - pip*/**
  - py-lambda-packer.yaml
  - setuptools*/**
  - wheel*/**
  - README.md
  - reference
  - .buildkite
  -
